# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift 

cache: cocoapods

podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

env:
  - ACTION=build PLATFORM=iOS DESTINATION='platform=iOS Simulator,name=iPhone XS,OS=12.0'

script:
- set -o pipefail && xcodebuild -workspace Example/BiometricAuthenticator.xcworkspace -scheme BiometricAuthenticator-Example -destination "$DESTINATION" $ACTION | xcpretty
- pod lib lint
